// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/post/post.proto

package go_micro_service_post

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Post struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Slug                 string   `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Content              string   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Timestamp            int64    `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TagNames             []string `protobuf:"bytes,6,rep,name=tagNames,proto3" json:"tagNames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Post) Reset()         { *m = Post{} }
func (m *Post) String() string { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()    {}
func (*Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{0}
}

func (m *Post) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Post.Unmarshal(m, b)
}
func (m *Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Post.Marshal(b, m, deterministic)
}
func (m *Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Post.Merge(m, src)
}
func (m *Post) XXX_Size() int {
	return xxx_messageInfo_Post.Size(m)
}
func (m *Post) XXX_DiscardUnknown() {
	xxx_messageInfo_Post.DiscardUnknown(m)
}

var xxx_messageInfo_Post proto.InternalMessageInfo

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Post) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Post) GetTagNames() []string {
	if m != nil {
		return m.TagNames
	}
	return nil
}

type SaveRequest struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{1}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

type SaveResponse struct {
	Post                 *Post    `protobuf:"bytes,1,opt,name=post,proto3" json:"post,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_de323a772ac9b83f, []int{2}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

func init() {
	proto.RegisterType((*Post)(nil), "go.micro.service.post.Post")
	proto.RegisterType((*SaveRequest)(nil), "go.micro.service.post.SaveRequest")
	proto.RegisterType((*SaveResponse)(nil), "go.micro.service.post.SaveResponse")
}

func init() { proto.RegisterFile("proto/post/post.proto", fileDescriptor_de323a772ac9b83f) }

var fileDescriptor_de323a772ac9b83f = []byte{
	// 250 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x4d, 0x4b, 0xf4, 0x30,
	0x10, 0xc7, 0x9f, 0xbe, 0xed, 0x63, 0x67, 0xc5, 0xc3, 0xe0, 0x42, 0x58, 0x3d, 0x94, 0x78, 0xe9,
	0x29, 0x0b, 0xeb, 0x5d, 0xbf, 0x81, 0x68, 0xbc, 0x79, 0xab, 0xdd, 0xa1, 0x04, 0xb6, 0x4d, 0xed,
	0xcc, 0xee, 0x27, 0xf1, 0x03, 0x4b, 0x52, 0x7c, 0x39, 0xa8, 0xe0, 0x25, 0xe4, 0xf7, 0xcf, 0xcc,
	0xf0, 0x1b, 0x02, 0xab, 0x71, 0xf2, 0xe2, 0x37, 0xa3, 0x67, 0x89, 0x87, 0x89, 0x8c, 0xab, 0xce,
	0x9b, 0xde, 0xb5, 0x93, 0x37, 0x4c, 0xd3, 0xd1, 0xb5, 0x64, 0xc2, 0xa3, 0x7e, 0x4d, 0x20, 0xbf,
	0xf7, 0x2c, 0x78, 0x06, 0xa9, 0xdb, 0xa9, 0xa4, 0x4a, 0xea, 0xd2, 0xa6, 0x6e, 0x87, 0xe7, 0x50,
	0x88, 0x93, 0x3d, 0xa9, 0x34, 0x46, 0x33, 0x20, 0x42, 0xce, 0xfb, 0x43, 0xa7, 0xb2, 0x18, 0xc6,
	0x3b, 0x2a, 0xf8, 0xdf, 0xfa, 0x41, 0x68, 0x10, 0x95, 0xc7, 0xf8, 0x1d, 0xf1, 0x12, 0x4a, 0x71,
	0x3d, 0xb1, 0x34, 0xfd, 0xa8, 0x8a, 0x2a, 0xa9, 0x33, 0xfb, 0x19, 0xe0, 0x1a, 0x4e, 0xa4, 0xe9,
	0xee, 0x9a, 0x9e, 0x58, 0x2d, 0xaa, 0xac, 0x2e, 0xed, 0x07, 0xeb, 0x1b, 0x58, 0x3e, 0x36, 0x47,
	0xb2, 0xf4, 0x72, 0x20, 0x16, 0xdc, 0x40, 0x1e, 0x6c, 0xa3, 0xde, 0x72, 0x7b, 0x61, 0xbe, 0xdd,
	0xc5, 0x84, 0x3d, 0x6c, 0x2c, 0xd4, 0xb7, 0x70, 0x3a, 0xf7, 0xf3, 0xe8, 0x07, 0xa6, 0x3f, 0x0f,
	0xd8, 0x3e, 0x41, 0x11, 0x88, 0xf1, 0x01, 0xf2, 0x30, 0x09, 0xf5, 0x0f, 0x3d, 0x5f, 0x34, 0xd7,
	0x57, 0xbf, 0xd6, 0xcc, 0x2a, 0xfa, 0xdf, 0xf3, 0x22, 0xfe, 0xc8, 0xf5, 0x5b, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x2d, 0x8e, 0x3c, 0x48, 0xaa, 0x01, 0x00, 0x00,
}
